apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    app: jenkins
spec:
  capacity:
    storage: 2Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadWriteMany # Access modes are defined below
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.1.13 # Please change this to your NFS server
    path: /srv/nfs4/data/jenkins # Please change this to the relevant share