apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  accessModes:
    - ReadWriteMany # Access modes for volumes is defined under Persistent Volumes
  resources:
    requests:
      storage: 2Gi # volume size requested